# work flow action will run for deployment
name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # set the fetch-depth for actions/checkout@master to be sure you retrieve all commits to look for the semver commit message.
          fetch-depth: '0'

      # install dependencies
      - name: Install dependencies
        run: npm install

      # Build lambda
      - name: Build lambda
        run: npm run build && npm run build:lambda

      # Archive build lambda artifacts
      - name: Archive lambda artifacts
        uses: actions/upload-artifact@v1
        with:
          name: lambda
          path: ./lambda

      # sync to s3 for deployment of the zip file
      - name: Sync lambda to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'lambda'
          DEST_DIR: "tw-syncer"

      # Bump version when deploy successful
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # Generate change logs
      - name: Generate chagne logs
        run: |
          npm run version

        # Archive change logs
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md

      # Create release
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump-version.outputs.new_tag }}
          release_name: Release ${{ steps.bump-version.outputs.new_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  release:
    needs: deploy
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install dependencies
      - name: Install dependencies
        run: npm install

      # build
      - name: Build
        run: npm run build && npm run build:lambda

      # generate api doc
      - name: Generate API HTML doc
        run: npm run doc

      # Archive doc artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: doc
          path: ./doc

      # Build github pages
      - name: Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
